<?php

namespace Academic\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Academic\UserBundle\Entity\Role;
use Doctrine\ORM\Query\Expr\Join;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function getAdminRole()
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder();

        $q
            ->from('AcademicUserBundle:Role', 'r')
            ->select('r')
            ->where('r.role = :role')
            ->setParameter('role', 'ROLE_ADMIN');
         $role = $q->getQuery()->getSingleResult();

        return $role;
    }

    public function getManagerRole()
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder();

        $q
            ->from('AcademicUserBundle:Role', 'r')
            ->select('r')
            ->where('r.role = :role')
            ->setParameter('role', 'ROLE_MANAGER');
        $role = $q->getQuery()->getSingleResult();

        return $role;
    }

    public function getOperatorRole()
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder();

        $q
            ->from('AcademicUserBundle:Role', 'r')
            ->select('r')
            ->where('r.role = :role')
            ->setParameter('role', 'ROLE_USER');
        $role = $q->getQuery()->getSingleResult();

        return $role;
    }
}
