<?php

namespace Academic\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function loadUserByUsername($username)
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder();

        $q
            ->from('AcademicUserBundle:User', 'u')
            ->select('u')
            ->where('u.username = :username')
            ->setParameter('username', $username);
        try {
            $user = $q->getQuery()->getSingleResult();
        } catch (NoResultException $e) {
            $user = new User();
        }

        return $user;
    }
}
