<?php

namespace Academic\ProjectBundle\Entity\Issue;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Academic\ProjectBundle\Entity\Issue\Activity;
use Doctrine\ORM\Query\Expr\Join;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function getUserActivities($userId)
    {
        $qb =$this->getEntityManager()->createQueryBuilder();
        $qb
            ->from('AcademicProjectBundle:Issue\Activity','a')
            ->select('a')
            ->leftJoin('AcademicUserBundle:User', 'u', Join::WITH, 'u = a.user')
            ->where('u.id = :user ')
            ->setParameter('user', $userId);

        return $qb->getQuery()->getResult();
    }
}
