security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Academic\UserBundle\Entity\User:
          algorithm: bcrypt
          cost: 12

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Academic\UserBundle\Entity\User
                property: username
        administrators:
            entity: { class: AcademicUserBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
              login_path: login
              check_path: login_check
            logout:
                path:   logout
                target: login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/, roles: [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/userlist, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
