parameters:
#    academic_user.example.class: Academic\UserBundle\Example
    test.client.class: Academic\TestBundle\Test\Client

services:
    security.access.user_voter:
        class:      Academic\UserBundle\Security\Authorization\Voter\UserVoter
        public:     false
        tags:
           - { name: security.voter }
#    academic_user.example:
#        class: %academic_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
