parameters:
     test.client.class: Academic\TestBundle\Test\Client
#    academic_test.example.class: Academic\TestBundle\Example

services:
#    academic_test.example:
#        class: %academic_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
