academic_project:
    resource: "@AcademicProjectBundle/Controller/ProjectController.php"
    type:     annotation

academic_project_issue:
    resource: "@AcademicProjectBundle/Controller/IssueController.php"
    type:     annotation

academic_user_index:
    resource: "@AcademicProjectBundle/Controller/UserBundle/IndexController.php"
    type:     annotation

academic_user_user:
    resource: "@AcademicProjectBundle/Controller/UserBundle/UserController.php"
    type:     annotation
