parameters:
#    academic_project.example.class: Academic\ProjectBundle\Example
    test.client.class: Academic\TestBundle\Test\Client

services:
    security.access.project_voter:
        class:      Academic\ProjectBundle\Security\Authorization\Voter\ProjectVoter
        public:     false
        tags:
           - { name: security.voter }
#    academic_project.example:
#        class: %academic_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
